# lightning.pytorch==2.4.0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: false
  callbacks:
  - class_path: lightning.pytorch.callbacks.RichProgressBar
model:
  classes: 4
