# lightning.pytorch==2.4.0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: false
  callbacks:
  - class_path: utils.global_progress_bar.BetterProgressBar
model:
  classes: 4
model_checkpoint:
  save_last: false
  save_top_k: 0
model_checkpoint_dice_weighted:
  save_last: false
  save_top_k: 0
eval_classification_mode: MULTICLASS_MODE
