# lightning.pytorch==2.4.0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: false
  callbacks:
  - class_path: utils.global_progress_bar.BetterProgressBar
model:
  classes: 4
