# lightning.pytorch==2.4.0
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  callbacks:
  - class_path: lightning.pytorch.callbacks.DeviceStatsMonitor
    init_args:
      cpu_stats: null
  - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    init_args:
      logging_interval: epoch
      log_momentum: false
      log_weight_decay: false
  - class_path: utils.global_progress_bar.BetterProgressBar
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      log_graph: false
      default_hp_metric: false
  log_every_n_steps: 5
  plugins:
  - class_path: lightning.pytorch.plugins.io.AsyncCheckpointIO
    init_args:
      checkpoint_io: null

model:
  classes: 4
  scheduler: one_cycle
data:
  augment: true
model_checkpoint_val_loss:
  dirpath: null
  monitor: loss/val
  verbose: false
  save_last: false
  save_top_k: 1
  save_weights_only: true
  mode: min
  auto_insert_metric_name: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
  enable_version_counter: true
model_checkpoint_dice_weighted:
  dirpath: null
  monitor: val/dice_weighted_avg
  verbose: false
  save_last: false
  save_top_k: 1
  save_weights_only: true
  mode: max
  auto_insert_metric_name: false
  every_n_train_steps: null
  train_time_interval: null
  every_n_epochs: null
  save_on_train_epoch_end: null
  enable_version_counter: true
eval_classification_mode: MULTICLASS_MODE
