# lightning.pytorch==2.4.0
trainer:
  logger: false
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 1
  callbacks:
  - class_path: utils.global_progress_bar.BetterProgressBar
model:
  classes: 4
  scheduler: one_cycle
data:
  augment: true
model_checkpoint:
  save_last: false
  save_top_k: 0
model_checkpoint_dice_weighted:
  save_last: false
  save_top_k: 0
