# lightning.pytorch==2.4.0
trainer:
  max_epochs: 50
  check_val_every_n_epoch: 1
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: ./checkpoints/two-stream/lightning_logs
model:
  classes: 4
  total_epochs: 50
  num_frames: 30
data:
  data_dir: data/train_val/
  test_dir: data/test/
  indices_dir: data/indices/
dl_classification_mode: MULTICLASS_MODE
eval_classification_mode: MULTICLASS_MODE
