name: documentation
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements-cpu.txt
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          TZ=UTC sphinx-apidoc -f --remove-old -o docs/source/apidoc ./src/
          TZ=UTC sphinx-build -M html docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          force_orphan: true

