name: docs
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements-cpu.txt
          pip install -r requirements-thirdparty.txt
          pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: |
          TZ=UTC PYTHONPATH="src/:thirdparty/VPS" sphinx-apidoc -f --remove-old -o docs/source/apidoc ./src/
          TZ=UTC PYTHONPATH="src/:thirdparty/VPS" sphinx-build -b html docs/source docs/build/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true

